# Generated by Django 6.1 on 2026-08-11 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_alter_guest_address_alter_guest_id_proof_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='age',
            field=models.PositiveIntegerField(default=18, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(120)]),
            preserve_default=False,
        ),
    ]
